-- Insert data into the planet table
INSERT INTO planet (planet_name, planet_description) VALUES
    ('Zorblax', 'A vibrant planet with floating islands and a kaleidoscope sky.'),
    ('Glimmervale', 'A realm of eternal twilight and glowing plants.'),
    ('Whimsyville', 'A land of perpetual parties and joyous creatures.'),
    ('Nebulon', 'A misty world where everything sparkles in shades of blue.'),
    ('Fantasia', 'A dimension of floating castles and crystal-clear rivers.'),
    ('Serenopia', 'A peaceful planet with endless fields of flowers.'),
    ('Lumenara', 'A bright planet full of luminescent creatures and habitats.'),
    ('Starhaven', 'A celestial sanctuary with auroras that paint the skies.'),
    ('Echoisphere', 'A world where sounds resonate in perfect harmony.'),
    ('Zephyra', 'Known for its gentle warm winds and tranquil sunsets.'),
    ('Auroria', 'A place of endless dawn with vibrant colors.'),
    ('Aquaflora', 'Where oceans and plant life coexist in symbiosis.'),
    ('Earth', 'The third planet from the Sun, home to a diverse range of organisms.'),
    ('Mars', 'A red planet often envisioned as a home to potential future colonies.'),
    ('Venus', 'A planet with a thick atmosphere of clouds and rustic landscapes.'),
    ('Brilliantia', 'A planet of radiant crystals and shimmering light.'),
    ('Mysteria', 'A world shrouded in enigma and hidden knowledge.'),
    ('Crescentia', 'A moonlit realm of perpetual twilight and intrigue.'),
    ('Elysium', 'A paradise of abundant flora and serene landscapes.'),
    ('Pyronia', 'A fiery world of lava flows and scorching heat.');


-- Insert data into the tea_blend table
INSERT INTO tea_blend (tea_blend_name, tea_blend_flavour, tea_blend_magic_effects) VALUES
    ('Stardust Brew', 'Minty with a hint of cosmic vanilla', 'Temporary invisibility'),
    ('Lunar Soothe', 'Floral and calming', 'Induces dreams of flight'),
    ('Galactic Spice', 'Spicy and warm', 'Gives a glowing aura'),
    ('Nebula Nectar', 'Sweet and tangy', 'Lets you speak the language of the stars'),
    ('Fantasia Froth', 'Creamy with hints of caramel', 'Grants temporary ability to float'),
    ('Solar Flare', 'Fiery and invigorating', 'Bursts of energy'),
    ('Twilight Tranquility', 'Herbal with a hint of lavender', 'Calms the mind'),
    ('Celestial Silence', 'Delicate and soothing', 'Enhances meditation'),
    ('Breezy Blossom', 'Floral and airy', 'Increases agility'),
    ('Sunflare Serenade', 'Bright and zesty', 'Rejuvenates energy'),
    ('Moonglow Miracle', 'Silky and buttery', 'Heightens senses'),
    ('Rainforest Rains', 'Earthy and rich', 'Grants understanding of nature'),
    ('Earl Grey', 'Citrus and bergamot', 'Enhances mental clarity and focus'),
    ('Chamomile', 'Floral and honey', 'Promotes calmness and aids sleep'),
    ('Mint Medley', 'Refreshing mint', 'Boosts energy and alertness'),
    ('Jasmine Green', 'Fragrant jasmine', 'Strengthens immune system'),
    ('Oolong', 'Full-bodied and floral', 'Improves digestion and skin health'),
    ('Aurora Bliss', 'Citrusy with a sparkle of mint', 'Makes auroras visible'),
    ('Mystic Mist', 'Smoky and mysterious', 'Reveals hidden secrets'),
    ('Crescent Delight', 'Earthy with a citrus twist', 'Induces visions of the future'),
    ('Elysian Elixir', 'Sweet and floral', 'Transforms energy to tranquility'),
    ('Pyro Brew', 'Spicy and hot', 'Ignites passion and creativity');

-- Insert data into the tea_party table
INSERT INTO tea_party (tea_party_name, description, tea_party_host_planet) VALUES
    ('Zorblax Carnival', 'A carnival of lights under swirling skies.', 1),
    ('Zorblax Soiree', 'A posh evening on Zorblax’s floating islands.', 1),
    ('Glimmervale Gathering', 'Connect with glowing flora and fauna.', 2),
    ('Glimmervale Serenity', 'A peaceful night under glowing trees.', 2),
    ('Glimmervale Celebration', 'Revelry among celestial wonders.', 2),
    ('Whimsyville Wonder', 'Joyous celebrations with whimsical touches.', 3),
    ('Whimsyville Extravaganza', 'Dance through Whimsyville’s night.', 3),
    ('Whimsyville Festival', 'Joy and color blend perfectly.', 3),
    ('Whimsyville Delight', 'Delight and whimsical surprises await you.', 3),
    ('Nebulon Gala', 'Stars dance upon the Nebulon night.', 4),
    ('Nebulon Dreamland', 'Dream under Nebulon’s sparking sky.', 4),
    ('Fantasia Frolic', 'Adventure among Fantasia’s castles.', 5),
    ('Fantasia Harmony', 'Harmony and unity in crystal’s song.', 5),
    ('Fantasia Carnival', 'Levitating fun beyond imaginations.', 5),
    ('Fantasia Revel', 'Revel amongst Fantasia’s floating peaks.', 5),
    ('Fantasia Experience', 'Castle landscapes meet aura melodies.', 5),
    ('Serenopia Concert', 'Find serenity in floral music.', 6),
    ('Serenopia Serenity', 'Be with peace amidst flowers.', 6),
    ('Lumenara Lightshow', 'Glow with Lumenara’s luminescent harmony.', 7),
    ('Lumenara Luminescence', 'Discover light amongst Lumenara creatures.', 7),
    ('Lumenara Radiance', 'Experience Lumenara’s lively glow.', 7),
    ('Starhaven Starlight', 'Star-studded moments steal the night.', 8),
    ('Starhaven Symphony', 'Celestial symphonies fill the air.', 8),
    ('Echoisphere Resonance', 'Sound and unity within Echoisphere.', 9),
    ('Echoisphere Choir', 'Voices blend with Echoisphere echoes.', 9),
    ('Echoisphere Experience', 'Discover Echoisphere’s harmonious sights.', 9),
    ('Zephyra Breeze', 'Whisper and sway with gentle Zephyra winds.', 10),
    ('Zephyra Zephyr', 'Experience Zephyra’s wind orchestras.', 10),
    ('Zephyra Ballet', 'Dance with hearts over Zephyra’s peaceful breeze.', 10),
    ('Aurorian Dawn', 'Bright sunrays dance upon the golden light.', 11),
    ('Aurorian Fire', 'Warmth and light cascade across Auroria.', 11),
    ('Aquaflora Flow', 'Flow with Aquaflora’s streams and blooms.', 12),
    ('Aquaflora Symphonia', 'Rivers create symphonies under Aquaflora’s light.', 12),
    ('Aquaflora Dance', 'Immerse and dance within Aquaflora’s embrace.', 12),
    ('Aquaflora Tranquility', 'Tranquility reigns high in hydroland.', 12),
    ('Earthly Grounding', 'Connect with Earth’s fertile grounding.', 13),
    ('Earthly Celebration', 'Join Earth’s blend of culture and grace.', 13),
    ('Earthly Evening', 'Diverse stories unfold among Earth’s valleys.', 13),
    ('Marsian Meet', 'Above red sands find success and joy.', 14),
    ('Marsian Night', 'Discover Mars’s celestial beat.', 14),
    ('Venusian Views', 'Capture vistas among Venus’s rarefied air.', 15),
    ('Venusian Colors', 'Colorful happenings delight upon Venus.', 15),
    ('Brilliantian Light', 'Light reflects uniquely among crystal paths.', 16),
    ('Brilliantian Show', 'Crystal journeys unveil romance.', 16),
    ('Brilliantian Emergence', 'Uncover light’s mysteries in glory’s glide.', 16),
    ('Brilliantian Sparkle', 'Glimmer shimmers across vision paths.', 16),
    ('Mysteria Dream', 'Discover yourself within Mysteria’s embrace.', 17),
    ('Mysteria Marvel', 'Wisdom cloaks Mysteria’s passages.', 17),
    ('Crescentia’s Revelry', 'Half-lit skies make vibrant jewels seen.', 18),
    ('Crescentia’s Balance', 'Moon shapes craft vivid balance.', 18),
    ('Crescentia’s Shadows', 'Dive within Crescentia’s veiled shadows.', 18),
    ('Elysium Reverie', 'Floral abundance meets calm delight.', 19),
    ('Elysium Balance', 'Dreams enliven Elysium’s sunny calm.', 19),
    ('Elysium Solace', 'Peace blossoms amidst Elysium’s gentle hold.', 19),
    ('Elysium Delight', 'Celebrate Elysium’s pastoral charm.', 19),
    ('Pyronia Pulse', 'Dance with Pyronia’s fiery embrace.', 20),
    ('Pyronia Night', 'Flames unveil hidden Pyronia paths.', 20),
    ('Pyronia Fête', 'Spirited flames illuminate the night.', 20),
    ('Pyronia Flow', 'Celebrate Pyronia’s energetic river.', 20);


-- Insert data into the tea_party_attendee table
INSERT INTO tea_party_attendee (tea_party_attendee_name, tea_party_attendee_home_planet_id) VALUES
    ('Quoxl', 1),
    ('Fizzlepop', 2),
    ('Glimmerina', 3),
    ('Nebulina', 4),
    ('Dreamweaver', 5),
    ('Seren', 6),
    ('Lumi', 7),
    ('Starlight', 8),
    ('Harmony', 9),
    ('Solara', 10),
    ('Aqua', 11),
    ('Breeze', 12),
    ('Dawn', 13),
    ('Alice', 14),
    ('Bob', 15),
    ('Chris', 1),
    ('Diana', 2),
    ('Eli', 3),
    ('Nova', 16),
    ('Enigma', 17),
    ('Luna', 18),
    ('Fauna', 19),
    ('Blaze', 20),
    ('Zephyr', 9),
    ('Aurora', 7),
    ('Myst', 4),
    ('Pax', 6),
    ('Lark', 11),
    ('Merlin', 14),
    ('Willow', 5);


-- Insert data into the tea_party_blend_assignment table
INSERT INTO tea_party_blend_assignment (tea_party_id, tea_blend_id) VALUES
    (1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 1), (3, 3),
    (4, 4), (4, 5), (5, 1), (5, 5), (6, 2), (6, 3),
    (7, 1), (7, 5), (8, 3), (8, 4), (9, 2), (9, 1),
    (10, 5), (10, 4), (11, 3), (11, 2), (12, 1), (12, 5),
    (13, 4), (13, 3), (14, 5), (14, 1), (15, 2), (15, 4),
    (16, 6), (16, 7), (17, 7), (18, 8), (19, 7), (20, 8), 
    (21, 9), (22, 10), (23, 11), (24, 12), (25, 11), 
    (26, 9), (27, 8), (28, 10), (29, 12),(30, 11), 
    (31, 12), (32, 9), (33, 8), (34, 10), (35, 11),
    (36, 13), (37, 14), (38, 15), (1, 1), (39, 16), 
    (39, 17), (40, 17), (40, 18), (41, 19),
    (41, 20), (42, 16), (42, 17), (43, 18), (43, 19),
    (44, 20), (44, 17), (45, 18), (45, 16);

-- Insert data into the tea_party_rating table
INSERT INTO tea_party_rating (tea_party_id, tea_party_attendee_id, rating) VALUES
(1, 1, 4),(1, 2, 2),(1, 17, 5),(1, 18, 1),(2, 3, 2),
(2, 4, 5),(2, 19, 5),(2, 5, 3),(3, 6, 5),(3, 7, 1),
(3, 20, 3),(3, 8, 4),(4, 9, 4),(4, 10, 4),(4, 21, 5),
(5, 11, 2),(5, 12, 2),(5, 22, 1),(5, 13, 4),(6, 14, 3),
(6, 23, 3),(6, 15, 2),(7, 16, 4),(7, 24, 4),(7, 17, 3),
(8, 18, 3),(8, 19, 1),(8, 25, 1),(9, 20, 5),(9, 26, 2),
(9, 21, 5),(10, 27, 3),(10, 22, 2),(10, 23, 5),
(11, 24, 3),(11, 28, 5),(11, 25, 5),(12, 26, 2),
(12, 27, 3),(12, 1, 5),(13, 2, 4),(13, 29, 1),(14, 30, 5),
(14, 3, 3),(14, 4, 1),(15, 5, 2),(15, 28, 1),(15, 6, 5),
(16, 9, 1),(16, 10, 5),(16, 7, 5),(17, 8, 1),(17, 11, 3),
(17, 13, 5),(18, 14, 2),(18, 15, 5),(18, 13, 1),(19, 14, 2),
(19, 16, 3),(19, 12, 1),(20, 17, 3),(20, 18, 5),(20, 19, 2),
(21, 20, 4),(21, 21, 5),(21, 23, 1),(22, 22, 5),(22, 5, 3),
(22, 6, 2),(23, 7, 5),(23, 8, 4),(23, 9, 3);


-- Insert data into the tea_party_host_assignment table
INSERT INTO tea_party_host_assignment (tea_party_host_id, tea_party_id) VALUES
    (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 16), (7, 17), (8, 18), 
    (9, 19), (10, 20), (11, 21), (12, 22), 
    (13, 23), (14, 24), (21, 39), (22, 40), (23, 41), (24, 42), (25, 43), 
    (21, 44), (22, 45);

-- Insert data into the tea_party_guest_assignment table
INSERT INTO tea_party_guest_assignment (tea_party_attendee_id, tea_party_id) VALUES
    (1, 1), (2, 1), (3, 2), (4, 2),
    (5, 3), (6, 3), (7, 4), (8, 4), (9, 5),
    (10, 6), (11, 6), (12, 7), (13, 7), (14, 8),
    (15, 9), (16, 9),
    (17, 10), (18, 10), (19, 11), (20, 11),
    (1, 12), (2, 12), (3, 13), (4, 13), (5, 14),
    (6, 14), (7, 15), (8, 15), (9, 16),
    (10, 17), (11, 17), (12, 18), (13, 18),
    (14, 19), (15, 19), (16, 20), (17, 20), 
    (18, 20),
    (19, 21), (20, 21), (1, 22), (2, 22),
    (3, 23), (4, 23), (5, 24), (6, 24), (7, 25),
    (8, 26), (9, 26), (10, 27), (11, 27), (12, 28),
    (13, 29), (14, 29), (15, 30), (16, 30),
    (17, 31), (18, 31), (19, 32), (20, 32), (1, 33),
    (2, 34), (3, 34), (4, 35), (5, 35), (6, 35),
    (7, 36), (8, 36), (9, 37), (10, 37),
    (11, 38), (12, 38), (13, 39), (14, 39),
    (15, 40), (16, 40), (17, 41), (18, 41), (19, 42),
    (20, 43), (1, 43), (2, 44), (3, 44),
    (4, 45), (5, 45), (6, 46), (7, 46), (8, 47),
    (9, 48), (10, 48), (11, 49), (12, 49), (13, 49),
    (14, 50), (15, 50), (16, 50), (17, 51), (18, 51);

-- Insert data into the planet_party_assignment table
INSERT INTO planet_party_assignment (planet_id, tea_party_id) VALUES
    (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 16), (7, 17), 
    (8, 18), (9, 19), (10, 20), (11, 21), (12, 22), 
    (13, 23), (14, 24), (16, 39), (17, 40), (18, 41), (19, 42), (20, 43), 
    (16, 44), (17, 45);
